<a href="https://colab.research.google.com/github/caraherrerapor/pytorch/blob/master/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:

import torch
import numpy as np

In [11]:
#construir matrix de 5x3
x = torch.empty(5,3)
print(x)


tensor([[3.2704e-36, 0.0000e+00, 2.3694e-38],
        [9.9812e+27, 1.9433e-19, 3.3738e-12],
        [7.4086e+28, 6.9397e+22, 1.7260e+25],
        [2.2856e+20, 5.0948e-14, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


In [13]:
#construir matriz aleatoria

x= torch.rand(5,3)
x

tensor([[0.2314, 0.9316, 0.7780],
        [0.6343, 0.0449, 0.5266],
        [0.9222, 0.3427, 0.1013],
        [0.9869, 0.9867, 0.1329],
        [0.7611, 0.9808, 0.6110]])

In [18]:
#construir una matrix con ceros


x = torch.zeros(5, 3 ,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [20]:
# construir directamente un tensor
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [22]:
print(x.size())

torch.Size([2])


In [26]:
x = torch.rand(5,3)
y = torch.rand(5,3)

print(x)
print()
print(y)
print()
sum = x+y
print(sum)

tensor([[0.8252, 0.2143, 0.5715],
        [0.6386, 0.8723, 0.8870],
        [0.9846, 0.3845, 0.8156],
        [0.3741, 0.0645, 0.4279],
        [0.4043, 0.3810, 0.7867]])

tensor([[0.3251, 0.3989, 0.4973],
        [0.5596, 0.2522, 0.3012],
        [0.8612, 0.6271, 0.7171],
        [0.3535, 0.0291, 0.7446],
        [0.6205, 0.4087, 0.3572]])

tensor([[1.1503, 0.6132, 1.0688],
        [1.1981, 1.1246, 1.1882],
        [1.8458, 1.0117, 1.5327],
        [0.7276, 0.0936, 1.1725],
        [1.0248, 0.7897, 1.1439]])


In [28]:
#otra forma de sumar en torch

sum = torch.add(x,y)
sum



tensor([[1.1503, 0.6132, 1.0688],
        [1.1981, 1.1246, 1.1882],
        [1.8458, 1.0117, 1.5327],
        [0.7276, 0.0936, 1.1725],
        [1.0248, 0.7897, 1.1439]])

In [33]:
# tomar filas de o columnas de un tensor

#columna
print("tensor = ",x)
print()
print(x[:,1])
print(x[:,2])
#fila

print(x[0,:])
print(x[3,:])

tensor =  tensor([[0.8252, 0.2143, 0.5715],
        [0.6386, 0.8723, 0.8870],
        [0.9846, 0.3845, 0.8156],
        [0.3741, 0.0645, 0.4279],
        [0.4043, 0.3810, 0.7867]])

tensor([0.2143, 0.8723, 0.3845, 0.0645, 0.3810])
tensor([0.5715, 0.8870, 0.8156, 0.4279, 0.7867])
tensor([0.8252, 0.2143, 0.5715])
tensor([0.3741, 0.0645, 0.4279])
